title: SF Feminist Book Club
email: radicalbarracuda@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Open source SF Feminist Book Club study guides and materials and a registry of our practices and the reasoning behind them.
baseurl: "/sf-feminist-book-club" # the subpath of your site, e.g. /blog
url: "https://radicalbarracuda.github.io"
permalink: /:categories/:title/
collections:
  events:
    output: true
    permalink: /:collection/:slug
  readings:
  study-guides:
    output: true
defaults:
  - scope:
      path: ""
      type: events
    values:
      layout: events
      categories: discussion
  - scope:
      path: ""
      type: study-guides
    values:
      layout: study-guides

# Build settings
gems:
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag
sass:
  sass_dir: _sass
kramdown:
  input: GFM
include: ['_pages', '_posts', '_resources']
exclude: ['Gemfile', 'Gemfile.lock', 'vendor']
