title: SF Feminist Book Club
email: radicalbarracuda@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Codify our practices and the reasoning behind them. Open source our study
  guides and materials.
baseurl: "/sf-feminist-book-club" # the subpath of your site, e.g. /blog
url: "https://radicalbarracuda.github.io"
permalink: /:title/
# Build settings
sass:
  sass_dir: _sass
kramdown:
  input: GFM
include: ['_pages', '_posts']
exclude: ['Gemfile', 'Gemfile.lock', 'vendor']
